#!/bin/sh

# General aliases.
alias cl="clear"
alias neo="neofetch"

# Confirm overwrite.
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# Directory list aliases.
alias ls='ls --color=auto'
alias ll='ls -Al --color=auto'

# Colored grep output.
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Services & disk size reader.
alias df='df -h'
alias free='free -m'
alias sysserv='systemctl list-unit-files --state=enabled'

# Git aliases.
alias m='git checkout master'
alias s='git checkout stable'

# Zsh aliases.
alias zsrc='nvim ~/.config/zsh/.zshrc'
alias zsupdate="find '$ZDOTDIR/plugins' -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# Nvim aliases.
alias suvi='sudo -E nvim'
alias virc='nvim ~/.config/nvim/init.lua'

# lf aliases.
alias lf='lfrun'

# Gest best package mirrors [Arch].
#alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
#alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
#alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
#alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
